// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpM5NGrQ0WI8jZE-45iZ-70AMkxfCNn8I',
    appId: '1:1079338267726:web:473a21e21ffb46e509ff1f',
    messagingSenderId: '1079338267726',
    projectId: 'markme-a780f',
    authDomain: 'markme-a780f.firebaseapp.com',
    storageBucket: 'markme-a780f.firebasestorage.app',
    measurementId: 'G-Q861ZML3QS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDIC29mQ0e9-HB2Q7ayuqGNqkZn7_WmGY',
    appId: '1:1079338267726:android:83edf177b98f440209ff1f',
    messagingSenderId: '1079338267726',
    projectId: 'markme-a780f',
    storageBucket: 'markme-a780f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZk9St-RH0nQy7LeK3OTGvabGujA8qYDA',
    appId: '1:1079338267726:ios:2b0af76e264a6e0009ff1f',
    messagingSenderId: '1079338267726',
    projectId: 'markme-a780f',
    storageBucket: 'markme-a780f.firebasestorage.app',
    iosBundleId: 'com.example.markme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZk9St-RH0nQy7LeK3OTGvabGujA8qYDA',
    appId: '1:1079338267726:ios:2b0af76e264a6e0009ff1f',
    messagingSenderId: '1079338267726',
    projectId: 'markme-a780f',
    storageBucket: 'markme-a780f.firebasestorage.app',
    iosBundleId: 'com.example.markme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpM5NGrQ0WI8jZE-45iZ-70AMkxfCNn8I',
    appId: '1:1079338267726:web:93305dd4f8a1001309ff1f',
    messagingSenderId: '1079338267726',
    projectId: 'markme-a780f',
    authDomain: 'markme-a780f.firebaseapp.com',
    storageBucket: 'markme-a780f.firebasestorage.app',
    measurementId: 'G-DRCTVGG9WH',
  );
}
